// Phase 2 gRPC contract for the in-house HNSW vector store.
//
// We deliberately keep this minimal: Add, Search, Stats. BulkLoad is a
// streaming convenience the Python indexer uses on cold start and after a
// `force` rebuild. Phase 5 will add Snapshot/Recover; Phase 6 will turn
// Search into a server-streaming RPC for batched queries.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: hnsw.proto

package hnswpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HnswService_Add_FullMethodName      = "/reposage.hnsw.v1.HnswService/Add"
	HnswService_BulkLoad_FullMethodName = "/reposage.hnsw.v1.HnswService/BulkLoad"
	HnswService_Search_FullMethodName   = "/reposage.hnsw.v1.HnswService/Search"
	HnswService_Stats_FullMethodName    = "/reposage.hnsw.v1.HnswService/Stats"
)

// HnswServiceClient is the client API for HnswService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HnswServiceClient interface {
	Add(ctx context.Context, in *AddRequest, opts ...grpc.CallOption) (*AddResponse, error)
	BulkLoad(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[AddRequest, BulkLoadResponse], error)
	Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error)
	Stats(ctx context.Context, in *StatsRequest, opts ...grpc.CallOption) (*StatsResponse, error)
}

type hnswServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHnswServiceClient(cc grpc.ClientConnInterface) HnswServiceClient {
	return &hnswServiceClient{cc}
}

func (c *hnswServiceClient) Add(ctx context.Context, in *AddRequest, opts ...grpc.CallOption) (*AddResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddResponse)
	err := c.cc.Invoke(ctx, HnswService_Add_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hnswServiceClient) BulkLoad(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[AddRequest, BulkLoadResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &HnswService_ServiceDesc.Streams[0], HnswService_BulkLoad_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AddRequest, BulkLoadResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type HnswService_BulkLoadClient = grpc.ClientStreamingClient[AddRequest, BulkLoadResponse]

func (c *hnswServiceClient) Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchResponse)
	err := c.cc.Invoke(ctx, HnswService_Search_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hnswServiceClient) Stats(ctx context.Context, in *StatsRequest, opts ...grpc.CallOption) (*StatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatsResponse)
	err := c.cc.Invoke(ctx, HnswService_Stats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HnswServiceServer is the server API for HnswService service.
// All implementations must embed UnimplementedHnswServiceServer
// for forward compatibility.
type HnswServiceServer interface {
	Add(context.Context, *AddRequest) (*AddResponse, error)
	BulkLoad(grpc.ClientStreamingServer[AddRequest, BulkLoadResponse]) error
	Search(context.Context, *SearchRequest) (*SearchResponse, error)
	Stats(context.Context, *StatsRequest) (*StatsResponse, error)
	mustEmbedUnimplementedHnswServiceServer()
}

// UnimplementedHnswServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHnswServiceServer struct{}

func (UnimplementedHnswServiceServer) Add(context.Context, *AddRequest) (*AddResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Add not implemented")
}
func (UnimplementedHnswServiceServer) BulkLoad(grpc.ClientStreamingServer[AddRequest, BulkLoadResponse]) error {
	return status.Error(codes.Unimplemented, "method BulkLoad not implemented")
}
func (UnimplementedHnswServiceServer) Search(context.Context, *SearchRequest) (*SearchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Search not implemented")
}
func (UnimplementedHnswServiceServer) Stats(context.Context, *StatsRequest) (*StatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Stats not implemented")
}
func (UnimplementedHnswServiceServer) mustEmbedUnimplementedHnswServiceServer() {}
func (UnimplementedHnswServiceServer) testEmbeddedByValue()                     {}

// UnsafeHnswServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HnswServiceServer will
// result in compilation errors.
type UnsafeHnswServiceServer interface {
	mustEmbedUnimplementedHnswServiceServer()
}

func RegisterHnswServiceServer(s grpc.ServiceRegistrar, srv HnswServiceServer) {
	// If the following call panics, it indicates UnimplementedHnswServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HnswService_ServiceDesc, srv)
}

func _HnswService_Add_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HnswServiceServer).Add(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HnswService_Add_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HnswServiceServer).Add(ctx, req.(*AddRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HnswService_BulkLoad_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(HnswServiceServer).BulkLoad(&grpc.GenericServerStream[AddRequest, BulkLoadResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type HnswService_BulkLoadServer = grpc.ClientStreamingServer[AddRequest, BulkLoadResponse]

func _HnswService_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HnswServiceServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HnswService_Search_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HnswServiceServer).Search(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HnswService_Stats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HnswServiceServer).Stats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HnswService_Stats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HnswServiceServer).Stats(ctx, req.(*StatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HnswService_ServiceDesc is the grpc.ServiceDesc for HnswService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HnswService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "reposage.hnsw.v1.HnswService",
	HandlerType: (*HnswServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Add",
			Handler:    _HnswService_Add_Handler,
		},
		{
			MethodName: "Search",
			Handler:    _HnswService_Search_Handler,
		},
		{
			MethodName: "Stats",
			Handler:    _HnswService_Stats_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "BulkLoad",
			Handler:       _HnswService_BulkLoad_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "hnsw.proto",
}
