// Phase 2 gRPC contract for the in-house HNSW vector store.
//
// We deliberately keep this minimal: Add, Search, Stats. BulkLoad is a
// streaming convenience the Python indexer uses on cold start and after a
// `force` rebuild. Phase 5 will add Snapshot/Recover; Phase 6 will turn
// Search into a server-streaming RPC for batched queries.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: hnsw.proto

package hnswpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Vector        []float32              `protobuf:"fixed32,2,rep,packed,name=vector,proto3" json:"vector,omitempty"` // float32 in proto3
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddRequest) Reset() {
	*x = AddRequest{}
	mi := &file_hnsw_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddRequest) ProtoMessage() {}

func (x *AddRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hnsw_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddRequest.ProtoReflect.Descriptor instead.
func (*AddRequest) Descriptor() ([]byte, []int) {
	return file_hnsw_proto_rawDescGZIP(), []int{0}
}

func (x *AddRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AddRequest) GetVector() []float32 {
	if x != nil {
		return x.Vector
	}
	return nil
}

type AddResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Size          uint64                 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddResponse) Reset() {
	*x = AddResponse{}
	mi := &file_hnsw_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddResponse) ProtoMessage() {}

func (x *AddResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hnsw_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddResponse.ProtoReflect.Descriptor instead.
func (*AddResponse) Descriptor() ([]byte, []int) {
	return file_hnsw_proto_rawDescGZIP(), []int{1}
}

func (x *AddResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *AddResponse) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type BulkLoadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Inserted      uint64                 `protobuf:"varint,1,opt,name=inserted,proto3" json:"inserted,omitempty"`
	Size          uint64                 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BulkLoadResponse) Reset() {
	*x = BulkLoadResponse{}
	mi := &file_hnsw_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BulkLoadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BulkLoadResponse) ProtoMessage() {}

func (x *BulkLoadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hnsw_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BulkLoadResponse.ProtoReflect.Descriptor instead.
func (*BulkLoadResponse) Descriptor() ([]byte, []int) {
	return file_hnsw_proto_rawDescGZIP(), []int{2}
}

func (x *BulkLoadResponse) GetInserted() uint64 {
	if x != nil {
		return x.Inserted
	}
	return 0
}

func (x *BulkLoadResponse) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

type SearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vector        []float32              `protobuf:"fixed32,1,rep,packed,name=vector,proto3" json:"vector,omitempty"`
	TopK          uint32                 `protobuf:"varint,2,opt,name=top_k,json=topK,proto3" json:"top_k,omitempty"`
	EfSearch      uint32                 `protobuf:"varint,3,opt,name=ef_search,json=efSearch,proto3" json:"ef_search,omitempty"` // 0 → use server default
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_hnsw_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hnsw_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_hnsw_proto_rawDescGZIP(), []int{3}
}

func (x *SearchRequest) GetVector() []float32 {
	if x != nil {
		return x.Vector
	}
	return nil
}

func (x *SearchRequest) GetTopK() uint32 {
	if x != nil {
		return x.TopK
	}
	return 0
}

func (x *SearchRequest) GetEfSearch() uint32 {
	if x != nil {
		return x.EfSearch
	}
	return 0
}

type SearchHit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Distance      float32                `protobuf:"fixed32,2,opt,name=distance,proto3" json:"distance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchHit) Reset() {
	*x = SearchHit{}
	mi := &file_hnsw_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchHit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchHit) ProtoMessage() {}

func (x *SearchHit) ProtoReflect() protoreflect.Message {
	mi := &file_hnsw_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchHit.ProtoReflect.Descriptor instead.
func (*SearchHit) Descriptor() ([]byte, []int) {
	return file_hnsw_proto_rawDescGZIP(), []int{4}
}

func (x *SearchHit) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SearchHit) GetDistance() float32 {
	if x != nil {
		return x.Distance
	}
	return 0
}

type SearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hits          []*SearchHit           `protobuf:"bytes,1,rep,name=hits,proto3" json:"hits,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_hnsw_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hnsw_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_hnsw_proto_rawDescGZIP(), []int{5}
}

func (x *SearchResponse) GetHits() []*SearchHit {
	if x != nil {
		return x.Hits
	}
	return nil
}

type StatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsRequest) Reset() {
	*x = StatsRequest{}
	mi := &file_hnsw_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsRequest) ProtoMessage() {}

func (x *StatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hnsw_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsRequest.ProtoReflect.Descriptor instead.
func (*StatsRequest) Descriptor() ([]byte, []int) {
	return file_hnsw_proto_rawDescGZIP(), []int{6}
}

type StatsResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Size           uint64                 `protobuf:"varint,1,opt,name=size,proto3" json:"size,omitempty"`
	Dim            uint32                 `protobuf:"varint,2,opt,name=dim,proto3" json:"dim,omitempty"`
	Model          string                 `protobuf:"bytes,3,opt,name=model,proto3" json:"model,omitempty"`
	M              uint32                 `protobuf:"varint,4,opt,name=m,proto3" json:"m,omitempty"`
	EfConstruction uint32                 `protobuf:"varint,5,opt,name=ef_construction,json=efConstruction,proto3" json:"ef_construction,omitempty"`
	EfSearch       uint32                 `protobuf:"varint,6,opt,name=ef_search,json=efSearch,proto3" json:"ef_search,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StatsResponse) Reset() {
	*x = StatsResponse{}
	mi := &file_hnsw_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsResponse) ProtoMessage() {}

func (x *StatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_hnsw_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsResponse.ProtoReflect.Descriptor instead.
func (*StatsResponse) Descriptor() ([]byte, []int) {
	return file_hnsw_proto_rawDescGZIP(), []int{7}
}

func (x *StatsResponse) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *StatsResponse) GetDim() uint32 {
	if x != nil {
		return x.Dim
	}
	return 0
}

func (x *StatsResponse) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *StatsResponse) GetM() uint32 {
	if x != nil {
		return x.M
	}
	return 0
}

func (x *StatsResponse) GetEfConstruction() uint32 {
	if x != nil {
		return x.EfConstruction
	}
	return 0
}

func (x *StatsResponse) GetEfSearch() uint32 {
	if x != nil {
		return x.EfSearch
	}
	return 0
}

var File_hnsw_proto protoreflect.FileDescriptor

const file_hnsw_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"hnsw.proto\x12\x10reposage.hnsw.v1\"4\n" +
	"\n" +
	"AddRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06vector\x18\x02 \x03(\x02R\x06vector\"1\n" +
	"\vAddResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x04R\x04size\"B\n" +
	"\x10BulkLoadResponse\x12\x1a\n" +
	"\binserted\x18\x01 \x01(\x04R\binserted\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x04R\x04size\"Y\n" +
	"\rSearchRequest\x12\x16\n" +
	"\x06vector\x18\x01 \x03(\x02R\x06vector\x12\x13\n" +
	"\x05top_k\x18\x02 \x01(\rR\x04topK\x12\x1b\n" +
	"\tef_search\x18\x03 \x01(\rR\befSearch\"7\n" +
	"\tSearchHit\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bdistance\x18\x02 \x01(\x02R\bdistance\"A\n" +
	"\x0eSearchResponse\x12/\n" +
	"\x04hits\x18\x01 \x03(\v2\x1b.reposage.hnsw.v1.SearchHitR\x04hits\"\x0e\n" +
	"\fStatsRequest\"\x9f\x01\n" +
	"\rStatsResponse\x12\x12\n" +
	"\x04size\x18\x01 \x01(\x04R\x04size\x12\x10\n" +
	"\x03dim\x18\x02 \x01(\rR\x03dim\x12\x14\n" +
	"\x05model\x18\x03 \x01(\tR\x05model\x12\f\n" +
	"\x01m\x18\x04 \x01(\rR\x01m\x12'\n" +
	"\x0fef_construction\x18\x05 \x01(\rR\x0eefConstruction\x12\x1b\n" +
	"\tef_search\x18\x06 \x01(\rR\befSearch2\xb8\x02\n" +
	"\vHnswService\x12B\n" +
	"\x03Add\x12\x1c.reposage.hnsw.v1.AddRequest\x1a\x1d.reposage.hnsw.v1.AddResponse\x12N\n" +
	"\bBulkLoad\x12\x1c.reposage.hnsw.v1.AddRequest\x1a\".reposage.hnsw.v1.BulkLoadResponse(\x01\x12K\n" +
	"\x06Search\x12\x1f.reposage.hnsw.v1.SearchRequest\x1a .reposage.hnsw.v1.SearchResponse\x12H\n" +
	"\x05Stats\x12\x1e.reposage.hnsw.v1.StatsRequest\x1a\x1f.reposage.hnsw.v1.StatsResponseB4Z2github.com/AndyUneducated/repo-sage/go-hnsw/hnswpbb\x06proto3"

var (
	file_hnsw_proto_rawDescOnce sync.Once
	file_hnsw_proto_rawDescData []byte
)

func file_hnsw_proto_rawDescGZIP() []byte {
	file_hnsw_proto_rawDescOnce.Do(func() {
		file_hnsw_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hnsw_proto_rawDesc), len(file_hnsw_proto_rawDesc)))
	})
	return file_hnsw_proto_rawDescData
}

var file_hnsw_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_hnsw_proto_goTypes = []any{
	(*AddRequest)(nil),       // 0: reposage.hnsw.v1.AddRequest
	(*AddResponse)(nil),      // 1: reposage.hnsw.v1.AddResponse
	(*BulkLoadResponse)(nil), // 2: reposage.hnsw.v1.BulkLoadResponse
	(*SearchRequest)(nil),    // 3: reposage.hnsw.v1.SearchRequest
	(*SearchHit)(nil),        // 4: reposage.hnsw.v1.SearchHit
	(*SearchResponse)(nil),   // 5: reposage.hnsw.v1.SearchResponse
	(*StatsRequest)(nil),     // 6: reposage.hnsw.v1.StatsRequest
	(*StatsResponse)(nil),    // 7: reposage.hnsw.v1.StatsResponse
}
var file_hnsw_proto_depIdxs = []int32{
	4, // 0: reposage.hnsw.v1.SearchResponse.hits:type_name -> reposage.hnsw.v1.SearchHit
	0, // 1: reposage.hnsw.v1.HnswService.Add:input_type -> reposage.hnsw.v1.AddRequest
	0, // 2: reposage.hnsw.v1.HnswService.BulkLoad:input_type -> reposage.hnsw.v1.AddRequest
	3, // 3: reposage.hnsw.v1.HnswService.Search:input_type -> reposage.hnsw.v1.SearchRequest
	6, // 4: reposage.hnsw.v1.HnswService.Stats:input_type -> reposage.hnsw.v1.StatsRequest
	1, // 5: reposage.hnsw.v1.HnswService.Add:output_type -> reposage.hnsw.v1.AddResponse
	2, // 6: reposage.hnsw.v1.HnswService.BulkLoad:output_type -> reposage.hnsw.v1.BulkLoadResponse
	5, // 7: reposage.hnsw.v1.HnswService.Search:output_type -> reposage.hnsw.v1.SearchResponse
	7, // 8: reposage.hnsw.v1.HnswService.Stats:output_type -> reposage.hnsw.v1.StatsResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_hnsw_proto_init() }
func file_hnsw_proto_init() {
	if File_hnsw_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hnsw_proto_rawDesc), len(file_hnsw_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_hnsw_proto_goTypes,
		DependencyIndexes: file_hnsw_proto_depIdxs,
		MessageInfos:      file_hnsw_proto_msgTypes,
	}.Build()
	File_hnsw_proto = out.File
	file_hnsw_proto_goTypes = nil
	file_hnsw_proto_depIdxs = nil
}
