# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: hnsw.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'hnsw.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nhnsw.proto\x12\x10reposage.hnsw.v1\"(\n\nAddRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0e\n\x06vector\x18\x02 \x03(\x02\"\'\n\x0b\x41\x64\x64Response\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\x0c\n\x04size\x18\x02 \x01(\x04\"2\n\x10\x42ulkLoadResponse\x12\x10\n\x08inserted\x18\x01 \x01(\x04\x12\x0c\n\x04size\x18\x02 \x01(\x04\"A\n\rSearchRequest\x12\x0e\n\x06vector\x18\x01 \x03(\x02\x12\r\n\x05top_k\x18\x02 \x01(\r\x12\x11\n\tef_search\x18\x03 \x01(\r\")\n\tSearchHit\x12\n\n\x02id\x18\x01 \x01(\t\x12\x10\n\x08\x64istance\x18\x02 \x01(\x02\";\n\x0eSearchResponse\x12)\n\x04hits\x18\x01 \x03(\x0b\x32\x1b.reposage.hnsw.v1.SearchHit\"\x0e\n\x0cStatsRequest\"p\n\rStatsResponse\x12\x0c\n\x04size\x18\x01 \x01(\x04\x12\x0b\n\x03\x64im\x18\x02 \x01(\r\x12\r\n\x05model\x18\x03 \x01(\t\x12\t\n\x01m\x18\x04 \x01(\r\x12\x17\n\x0f\x65\x66_construction\x18\x05 \x01(\r\x12\x11\n\tef_search\x18\x06 \x01(\r2\xb8\x02\n\x0bHnswService\x12\x42\n\x03\x41\x64\x64\x12\x1c.reposage.hnsw.v1.AddRequest\x1a\x1d.reposage.hnsw.v1.AddResponse\x12N\n\x08\x42ulkLoad\x12\x1c.reposage.hnsw.v1.AddRequest\x1a\".reposage.hnsw.v1.BulkLoadResponse(\x01\x12K\n\x06Search\x12\x1f.reposage.hnsw.v1.SearchRequest\x1a .reposage.hnsw.v1.SearchResponse\x12H\n\x05Stats\x12\x1e.reposage.hnsw.v1.StatsRequest\x1a\x1f.reposage.hnsw.v1.StatsResponseB4Z2github.com/AndyUneducated/repo-sage/go-hnsw/hnswpbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hnsw_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z2github.com/AndyUneducated/repo-sage/go-hnsw/hnswpb'
  _globals['_ADDREQUEST']._serialized_start=32
  _globals['_ADDREQUEST']._serialized_end=72
  _globals['_ADDRESPONSE']._serialized_start=74
  _globals['_ADDRESPONSE']._serialized_end=113
  _globals['_BULKLOADRESPONSE']._serialized_start=115
  _globals['_BULKLOADRESPONSE']._serialized_end=165
  _globals['_SEARCHREQUEST']._serialized_start=167
  _globals['_SEARCHREQUEST']._serialized_end=232
  _globals['_SEARCHHIT']._serialized_start=234
  _globals['_SEARCHHIT']._serialized_end=275
  _globals['_SEARCHRESPONSE']._serialized_start=277
  _globals['_SEARCHRESPONSE']._serialized_end=336
  _globals['_STATSREQUEST']._serialized_start=338
  _globals['_STATSREQUEST']._serialized_end=352
  _globals['_STATSRESPONSE']._serialized_start=354
  _globals['_STATSRESPONSE']._serialized_end=466
  _globals['_HNSWSERVICE']._serialized_start=469
  _globals['_HNSWSERVICE']._serialized_end=781
# @@protoc_insertion_point(module_scope)
