# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import hnsw_pb2 as hnsw__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in hnsw_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class HnswServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Add = channel.unary_unary(
                '/reposage.hnsw.v1.HnswService/Add',
                request_serializer=hnsw__pb2.AddRequest.SerializeToString,
                response_deserializer=hnsw__pb2.AddResponse.FromString,
                _registered_method=True)
        self.BulkLoad = channel.stream_unary(
                '/reposage.hnsw.v1.HnswService/BulkLoad',
                request_serializer=hnsw__pb2.AddRequest.SerializeToString,
                response_deserializer=hnsw__pb2.BulkLoadResponse.FromString,
                _registered_method=True)
        self.Search = channel.unary_unary(
                '/reposage.hnsw.v1.HnswService/Search',
                request_serializer=hnsw__pb2.SearchRequest.SerializeToString,
                response_deserializer=hnsw__pb2.SearchResponse.FromString,
                _registered_method=True)
        self.Stats = channel.unary_unary(
                '/reposage.hnsw.v1.HnswService/Stats',
                request_serializer=hnsw__pb2.StatsRequest.SerializeToString,
                response_deserializer=hnsw__pb2.StatsResponse.FromString,
                _registered_method=True)


class HnswServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Add(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BulkLoad(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Search(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Stats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HnswServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Add': grpc.unary_unary_rpc_method_handler(
                    servicer.Add,
                    request_deserializer=hnsw__pb2.AddRequest.FromString,
                    response_serializer=hnsw__pb2.AddResponse.SerializeToString,
            ),
            'BulkLoad': grpc.stream_unary_rpc_method_handler(
                    servicer.BulkLoad,
                    request_deserializer=hnsw__pb2.AddRequest.FromString,
                    response_serializer=hnsw__pb2.BulkLoadResponse.SerializeToString,
            ),
            'Search': grpc.unary_unary_rpc_method_handler(
                    servicer.Search,
                    request_deserializer=hnsw__pb2.SearchRequest.FromString,
                    response_serializer=hnsw__pb2.SearchResponse.SerializeToString,
            ),
            'Stats': grpc.unary_unary_rpc_method_handler(
                    servicer.Stats,
                    request_deserializer=hnsw__pb2.StatsRequest.FromString,
                    response_serializer=hnsw__pb2.StatsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'reposage.hnsw.v1.HnswService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('reposage.hnsw.v1.HnswService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class HnswService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Add(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/reposage.hnsw.v1.HnswService/Add',
            hnsw__pb2.AddRequest.SerializeToString,
            hnsw__pb2.AddResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BulkLoad(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/reposage.hnsw.v1.HnswService/BulkLoad',
            hnsw__pb2.AddRequest.SerializeToString,
            hnsw__pb2.BulkLoadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Search(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/reposage.hnsw.v1.HnswService/Search',
            hnsw__pb2.SearchRequest.SerializeToString,
            hnsw__pb2.SearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Stats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/reposage.hnsw.v1.HnswService/Stats',
            hnsw__pb2.StatsRequest.SerializeToString,
            hnsw__pb2.StatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
